# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Homcg5BUrqSS5VVthYC-bxjg4LuxkRjQ
"""

import pickle
import sys
#doc_new = ['obama is running for president in 2016']

var =sys.argv[1]


#function to run for prediction
def detecting_fake_news(var):    
#retrieving the best model for prediction call
    with open("./final_model.sav", 'rb') as f:
      load_model = pickle.load(f)
    prediction = load_model.predict([var])
    prob = load_model.predict_proba([var])

    return (print("The given statement is ",prediction[0]))


if __name__ == '__main__':
    detecting_fake_news(var)